image: node:10

cache:
  paths:
    - node_modules/
    - .yarn

variables:
  mongoServer: "mongo:27017"

stages:
  - test
  - audit

test:
  stage: test
  services:
    - mongo:latest
  script:
    - yarn install --pure-lockfile --cache-folder .yarn
    - yarn test:ci
  coverage: '/^Statements\s*:\s*([^%]+)/'

audit:
  stage: audit
  only:
  - schedules
  script:
    - yarn audit
